### ISSUE TITLE
[질문] 번역 시 용어 부연 설명에 대한 사항

### ISSUE THREAD

**Issue by damilog** [11st-corp/tc39-ko#1]
번역 과정에서 낯선 용어가 있었는데요. 해당 용어 하단에 풀이를 적어줘도 될까요? 
아님 번역 문서에는 번역 내용만 들어가는 게 좋을까요?

**Comment by huckjoo** [comment]
번역 문서에 주석처럼 풀이를 적어주는게 좋다고 생각합니다. 풀이도 번역의 일부라고 생각해요~~

**Comment by hochan222** [comment]
번역 문서에는 최대한 원문 그대로 적어주는것은 어떤가요? 원문과 동일하게 적지 않는다면, 내용이 점점 길어져 핵심을 전달하지 못할 수 도 있을것같기도 하고 낯선 용어의 기준이 사람마다 다르다고 생각합니다.

summary 폴더에서 풀이하는건 어떨까요? 저는 사전 지식 항목에 적어두었습니다.. 음..

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/22424891/225174236-d6ccdb34-2613-438c-a31d-e9887a95a5b9.png">

**Comment by huckjoo** [comment]
내용이 길어져서 핵심을 전달하지 못할 수 있다는 것에 동의합니다.

![IMG_6351 2](https://user-images.githubusercontent.com/76726411/225176320-c53c2a6d-c1b9-4c15-8eff-711641183b6b.jpg)

그러면 위 그림과 같이 아래에 간단하게 적어주는건 어떤가요?? (옮긴이) 표시를 한다던가 하는 식으로요. 이렇게 하면 본문은 완벽히 동일하니까 영어로 된 본문을 찾아볼 필요도 없고, 사전 지식이 달라도 밑에 주석처럼 작성한 부분은 안보면 그만이니까 호찬님이 걱정하시는 부분도 해결될 것 같습니다. 

마크다운으로는 이렇게 하면 되지 않을까요<sup>[1](#footnote_1)</sup>

summary 폴더에 풀이하는것도 좋은데 그럼 두개를 봐야하해서... 하나의 파일로 설명이 된다면 하나의 파일로 관리하는게 더 좋다고 생각해서요. 설명할게 너무 길어진다면 summary 폴더에 따로 작성하는게 좋아보이네요!

---
> <a name="footnote_1">1.</a> (옮긴이) 주석에 관한 설명...

**Comment by hochan222** [comment]
주신 이미지에서 숫자 9는 본문에서 어떻게 표현하면 좋을까요? (9)로 표시하기엔 원문에 혼동이 있을것같습니다. 

간단한건 아래와 같이 작성해도 좋을것같습니다.

![image](https://user-images.githubusercontent.com/22424891/225186677-d20ebd5d-117e-400d-bd08-c2617a45b9fc.png)

https://github.com/11st-corp/tc39-ko/pull/2/files#r1136424283

**Comment by huckjoo** [comment]
위에서 말씀드린것과 같이

본문내용중 일부<sup>[9](#footnote_1)</sup>

---
 <a name="footnote_1">9.</a> 내용~~~
 
이렇게 하면 어떤가요? sup 태그를 tc39 본문에서 사용하지 않는것 같아서요

**Comment by hochan222** [comment]
좋습니다~!

**Comment by damilog** [comment]
일부<sup>[9](#footnote_1)</sup>

오 마크다운으로 이렇게 작성할 수도 있군요. 👍
원문을 최대한 유지하고 참고 사항은 summary에 추가하되
꼭 필요한 용어 풀이일 경우  위 표기로 추가하도록하겠습니다.
두 분 모두 좋은 의견 감사드립니다!

**Comment by hochan222** [comment]
`<sup>[1][]</sup>` 이 방법은 어떤가요? 현재 혁주님께서 사용하신 방법은 원문의 가독성을 해치는것 같아서 하단으로 내렸습니다.

https://github.com/11st-corp/tc39-ko/pull/5#discussion_r1137325204 방법은 어떨지 의견 부탁드립니다.
