### ISSUE TITLE
[제안] 용어 번역: Motivation

### ISSUE THREAD

**Issue by huckjoo** [11st-corp/tc39-ko#10]
저는 Motivation 을 '동기'라고 번역했었는데
찬우님 번역을 보다보니까 '제안 동기'라고 번역하셨더라구요 근데 읽다보니까 '제안 동기'라고 하니까 더 잘 와닿는 것 같아서 '제안 동기'로 통일하는 것은 어떤가 제안합니다. 의견 부탁드려요~

**Comment by damilog** [comment]
좋습니다. 맥락에 맞는 번역이라고 생각합니다~

**Comment by damilog** [comment]
- 의미가 맞게 번역하는 것을 허용하되, glossary에 필수적으로 반영하기로 결정

**Comment by hochan222** [comment]
아직 용어집에 포함되지 않았기에 issue reopen합니다.

**Comment by huckjoo** [comment]
https://github.com/11st-corp/tc39-ko/commit/f994c745bfeb6fa5c21af5a5205300f005a84cd4
해당 커밋에서 덮어씌워지면서 지워진 것으로 확인했습니다.
제가 다시 추가해두었습니다 :)
