### ISSUE TITLE
[제안] 용어 번역: proposal

### ISSUE THREAD

**Issue by hochan222** [11st-corp/tc39-ko#13]
> This proposal is currently at [stage 4](https://github.com/tc39/ecma262) of the [process](https://tc39.github.io/process-document/), and will be included in ES 2017.

tc39 문서의 상단에 자주 나오는 `This proposal`을 `본 제안서는`으로 번역하는 것을 제안드립니다.

**Comment by huckjoo** [comment]
'본 제안'이나 '본 제안서'나 의미는 비슷한 것 같아서 둘 중에 하나로 통일만 되면 괜찮을 것 같습니다.

**Comment by hochan222** [comment]
답변이 너무 늦어져서 모두 죄송합니댜 ㅜㅜ.. 흑.. 벌써 일주일이 지났네요 ㅜㅜ

"stage 4에 올라간 상태의 문서"로 이미 정제가 완료되어 표준 스펙으로 발전되기 전 상태이므로 문서의 의미를 포함했습니다. 제안은 대게 문서로 작성되지 않으며, 제안서는 제안의 내용을 자세하게 서술하기에 "제안서"로 제안드렸습니다.

@chanuuuuu 님 의견에 동의하며, 이 때문에 본문의 상단에 처음 나오는 `This proposal`에 대해서만 제안서로 제안했고, 그 이후에 나오는 proposal은 제안으로 번역해도 좋아보입니다.

의견 부탁드려요!

**Comment by damilog** [comment]
첫 문장만 본 제안서, 
그외는 본 제안으로 작성
