### ISSUE TITLE
[제안] glossary 내 기술 영역 추가

### ISSUE THREAD

**Issue by damilog** [11st-corp/tc39-ko#21]
엄격 동등 비교(이미 glossary.md 내 `공통` 영역에서 사용), 비동기, 객체 구조 분해 할당, 트랜스파일러 등과 같은 기술 관련 단어를 모아서 관리하면 어떨까요? 

`## 기술` 로 생성하여 별도 표로 관리하는 것을 제안드립니다~!

**Comment by hochan222** [comment]
좋습니다~!
